services:
  app:
    image: traefbal-app
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.main-app.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.routers.main-app.middlewares=add-url-header,add-inb-h,add-path-h"
      - "traefik.http.middlewares.add-url-header.headers.customRequestHeaders.X-Source=app"
      - "traefik.http.middlewares.add-inb-h.headers.customRequestHeaders.X-App=traefbal"
      - "traefik.http.middlewares.add-inb-h.headers.customResponseHeaders.X-App=traefbal"
      - "traefik.http.middlewares.add-path-h.replacePathRegex.regex=^/(.*)"
      - "traefik.http.middlewares.add-path-h.replacePathRegex.replacement=$$1"
      - "traefik.http.services.main-app.loadbalancer.server.port=80"
  traefik:
    image: traefik:3.0
    container_name: traefik
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - app
    ports:
      - 8080:8080
      - 8000:80
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
