providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
api:
  insecure: true
  dashboard: true
entryPoints:
  web:
    address: ":80"
  metrics:
    address: ":8081"
metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true
    headerLabels:
      path: X-Replaced-Path
      app: X-App
